### ISSUE TITLE
Preserve file group, permission bits, and timestamps

### ISSUE THREAD

**Issue by adammoody** [ECP-VeloC/AXL#41]
If user applications are setting specific groups or permission bits on the source files, I'm guessing they'd like to have those properties preserved after a transfer.  We don't currently do this.

As for timestamps, I can imagine some apps might want to preserve those (use timestamp from the source files) and some apps might want to assign new timestamps when creating the destination files.

And then there are things like extended attributes, although that's probably much less of a concern (much smaller user base).

Not sure how any of the vendor APIs deal with this.

**Comment by tonyhutter** [comment]
Maybe the default guarantee should be "AXL preserves whatever your transfer type preserves" (which we should document), but then give the option to explicitly say "preserve timestamps" or "preserve XATTRs" or whatever in `AXL_Config()`.  That would work for most cases.  It wouldn't work in the case where you wanted different files in your file list to have different attributes preserved.  For that you'd have to add a flag value to AXL_Add() or something.  Like: `AXL_Add(id, src, dest, AXL_PRESERVE_XADDR | AXL_PRESERVE_PERMISSIONS)`.

I would vote in favour of just setting it globally in `AXL_Config()`, since the common case will be that they'd want the same attributes preserved for all their files.
